# Generated by Django 4.1.1 on 2022-09-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=5)),
                ('peso', models.CharField(max_length=15)),
                ('frecuencia_cardiaca', models.CharField(max_length=15)),
                ('spo2', models.CharField(max_length=15)),
                ('nivel_estres', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
    ]
